# Proximi.io iOS SDK — BINARY distribution podspec (CocoaPods).
#
# This file is regenerated per release by scripts/publish-binary-release.sh and
# committed to the distribution repo (proximiio/proximiio-sdk-ios-binary) beside
# Package.swift. The __PLACEHOLDER__ tokens are rewritten to this release's
# version, published Release-asset URL, and its SHA-256 checksum. Customers
# reference the tagged copy of this podspec (see distribution README) — no
# CocoaPods trunk push is required.
#
# Design (mirrors the SwiftPM package):
#   * vendored_frameworks ships the single flattened `ProximiioBinary.xcframework`
#     (the whole SDK; source is proprietary and never shipped);
#   * a one-line source shim is compiled into the public `Proximiio` module so
#     integrators keep writing `import Proximiio`. The `:http` pod source only
#     contains the xcframework zip, so the shim is materialised at install time
#     via `prepare_command` — this keeps the SwiftPM binary archive
#     byte-identical (same zip, same checksum for both toolchains);
#   * GRDB links from source in the consumer build and satisfies the binary's
#     storage symbols (matches the SwiftPM `from: "7.0.0"` pin).

Pod::Spec.new do |s|
  s.name             = 'Proximiio'
  s.version          = '6.0.0-beta.27'
  s.summary          = 'Proximi.io iOS SDK — indoor positioning, PDR, geofencing, and wayfinding.'
  s.description      = <<-DESC
    Precompiled binary distribution of the Proximi.io iOS SDK: indoor positioning,
    pedestrian dead reckoning (PDR), geofencing, route snapping, wayfinding, and
    offline venue packages. Ships as a single `ProximiioBinary.xcframework`; the
    source is proprietary and is not published.
  DESC
  s.homepage         = 'https://proximi.io'
  s.authors          = { 'Proximi.io' => 'support@proximi.io' }
  s.documentation_url = 'https://github.com/proximiio/proximiio-sdk-ios-binary'

  # Commercial license. The license text is embedded inline (not `:file =>`)
  # because the `:http` pod source contains only the xcframework zip — the
  # LICENSE file lives in the distribution repo, not in the downloaded archive.
  s.license          = {
    :type => 'Commercial',
    :text => <<-LICENSE
      Proximi.io iOS SDK — Proprietary, licensed not sold. Use is subject to a
      separate written commercial agreement with Proximi.io. See the LICENSE file
      in https://github.com/proximiio/proximiio-sdk-ios-binary for full terms.
    LICENSE
  }

  s.platform         = :ios, '15.0'
  s.swift_version    = '5.9'
  # The binary interface is emitted in Swift 6 language mode with library
  # evolution, so consumers must build with Xcode 16+ / Swift 6 toolchain.
  s.cocoapods_version = '>= 1.10.0'

  # Downloaded from the tagged GitHub Release of the distribution repo. CocoaPods
  # unzips the archive into the pod root; it contains `ProximiioBinary.xcframework`
  # at its top level. `:sha256` is the SHA-256 of the zip — the SAME value SwiftPM
  # pins via `swift package compute-checksum`, so both toolchains verify one digest.
  s.source           = { :http => 'https://github.com/proximiio/proximiio-sdk-ios-binary/releases/download/6.0.0-beta.27/ProximiioBinary.xcframework.zip', :sha256 => '2f4e2654ceedab4363efdb2c0bd3c2b98bdfcf012924fc23ce7fb4a432d0cd28' }

  s.vendored_frameworks = 'ProximiioBinary.xcframework'

  # Thin source shim → compiled into the public `Proximiio` module so callers
  # write a single `import Proximiio`. Materialised at install time because the
  # `:http` source ships only the xcframework (keeps the SwiftPM zip identical).
  s.source_files     = 'Sources/Proximiio/**/*.swift'
  s.prepare_command  = <<~CMD
    set -e
    mkdir -p Sources/Proximiio
    printf '%s\\n' \
      '// Generated by the Proximiio podspec prepare_command.' \
      '// Re-exports the precompiled ProximiioBinary module under the public Proximiio name.' \
      '@_exported import ProximiioBinary' \
      > Sources/Proximiio/Exports.swift
  CMD

  # GRDB (open source, no Proximi.io IP) links from source in the consumer build.
  s.dependency 'GRDB.swift', '~> 7.0'
end
