# Proximi.io iOS SDK — BINARY distribution podspec (CocoaPods).
#
# This file is regenerated per release by scripts/publish-binary-release.sh and
# committed to the distribution repo (proximiio/proximiio-sdk-ios-binary) beside
# Package.swift. The __PLACEHOLDER__ tokens are rewritten to this release's
# version, published Release-asset URL, and its SHA-256 checksum. Customers
# reference the tagged copy of this podspec (see distribution README) — no
# CocoaPods trunk push is required.
#
# Design (mirrors the SwiftPM package):
#   * vendored_frameworks ships the single flattened `ProximiioBinary.xcframework`
#     (the whole SDK; source is proprietary and never shipped);
#   * a one-line source shim is compiled into the public `Proximiio` module so
#     integrators keep writing `import Proximiio`. The `:http` pod source only
#     contains the xcframework zip, so the shim is materialised at install time
#     via `prepare_command` — this keeps the SwiftPM binary archive
#     byte-identical (same zip, same checksum for both toolchains);
#   * NO third-party pod dependency. GRDB is compiled INTO the xcframework
#     (≈4 990 exported GRDB symbols, zero undefined; SQLite comes from
#     /usr/lib/libsqlite3.dylib), so declaring `GRDB.swift` here only made
#     CocoaPods build and link a second, unreachable copy into the app —
#     ~600 KB and 52 duplicate ObjC class registrations at launch.
#
# NO SHIM SUBSPECS, ON PURPOSE. The SwiftPM template vends shim products
# (`ProximiioCore`) so a downstream SwiftPM package can NAME a dependency; they
# are aliases for the one flattened module, not boundaries. That has no
# CocoaPods equivalent worth building: a pod is ONE module (`module_name` is
# pod-level, not per-subspec), so vending `import ProximiioCore` here would
# mean a second pod wrapping the same xcframework — a second podspec, a second
# install entry — to gain a name no CocoaPods consumer asks for. CocoaPods and
# React Native integrators write `import Proximiio` and get the same whole
# flattened surface either way, so nothing is lost. This asymmetry is
# deliberate; it was not forgotten.

Pod::Spec.new do |s|
  s.name             = 'Proximiio'
  s.version          = '6.0.0-beta.38'
  s.summary          = 'Proximi.io iOS SDK — indoor positioning, PDR, geofencing, and wayfinding.'
  s.description      = <<-DESC
    Precompiled binary distribution of the Proximi.io iOS SDK: indoor positioning,
    pedestrian dead reckoning (PDR), geofencing, route snapping, wayfinding, and
    offline venue packages. Ships as a single `ProximiioBinary.xcframework`; the
    source is proprietary and is not published.
  DESC
  s.homepage         = 'https://proximi.io'
  s.authors          = { 'Proximi.io' => 'support@proximi.io' }
  s.documentation_url = 'https://github.com/proximiio/proximiio-sdk-ios-binary'

  # Commercial license. The license text is embedded inline (not `:file =>`)
  # because the `:http` pod source contains only the xcframework zip — the
  # LICENSE file lives in the distribution repo, not in the downloaded archive.
  s.license          = {
    :type => 'Commercial',
    :text => <<-LICENSE
      Proximi.io iOS SDK — Proprietary, licensed not sold. Use is subject to a
      separate written commercial agreement with Proximi.io. See the LICENSE file
      in https://github.com/proximiio/proximiio-sdk-ios-binary for full terms.
    LICENSE
  }

  s.platform         = :ios, '15.0'
  s.swift_version    = '6.0'
  # The binary interface is emitted in Swift 6 language mode with library
  # evolution, so consumers must build with Xcode 16+ / Swift 6 toolchain.
  s.cocoapods_version = '>= 1.10.0'

  # Downloaded from the tagged GitHub Release of the distribution repo. CocoaPods
  # unzips the archive into the pod root; it contains `ProximiioBinary.xcframework`
  # at its top level. `:sha256` is the SHA-256 of the zip — the SAME value SwiftPM
  # pins via `swift package compute-checksum`, so both toolchains verify one digest.
  s.source           = { :http => 'https://github.com/proximiio/proximiio-sdk-ios-binary/releases/download/6.0.0-beta.38/ProximiioBinary.xcframework.zip', :sha256 => 'b73106ccc0d8695e739a5d1e22b1e8ae47a1363ca6729ad0908af23ca08dca69' }

  s.vendored_frameworks = 'ProximiioBinary.xcframework'

  # Thin source shim → compiled into the public `Proximiio` module so callers
  # write a single `import Proximiio`. Materialised at install time because the
  # `:http` source ships only the xcframework (keeps the SwiftPM zip identical).
  s.source_files     = 'Sources/Proximiio/**/*.swift'
  s.prepare_command  = <<~CMD
    set -e
    mkdir -p Sources/Proximiio
    printf '%s\\n' \
      '// Generated by the Proximiio podspec prepare_command.' \
      '// Re-exports the precompiled ProximiioBinary module under the public Proximiio name.' \
      '@_exported import ProximiioBinary' \
      > Sources/Proximiio/Exports.swift
  CMD

  # No `s.dependency` line, deliberately — see the header. The vendored
  # xcframework already contains GRDB, and scripts/verify-binary-release.sh
  # fails the release if a GRDB dependency reappears in either manifest.
end
